name: PHPUnit 

on: [push]

jobs:
  build:
    name: PhpUnit

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: php-actions/composer@v5
    - uses: php-actions/phpunit@v9
      with:
        configuration: phpunit.xml.dist
